java  -XX:+UseZGC -XX:+ZGenerational -Xms1g -Xmx1g -XX:+ExitOnOutOfMemoryError \
-javaagent:./elastic-apm-agent-1.52.0.jar \
-Delastic.apm.service_name=rest-jpa \
-Delastic.apm.api_key=VlBiQk41VUItaGlrcklnXzBrSkM6eEtZM285Q2toNnhnbTlzcHIyMFFHZw== \
-Delastic.apm.server_url=https://my-observability-project-ae9eab.apm.us-east-1.aws.elastic.cloud:443 \
-Delastic.apm.environment=my-environment \
-Delastic.apm.application_packages=com.avanade \
-Delastic.apm.capture_body=all \
-Delastic.apm.capture_headers=true \
-Delastic.apm.allow_non_exemplary_http_headers=true \
-Delastic.apm.transaction_max_spans=500 \
-jar ../target/rest-jpa-0.0.1-SNAPSHOT.jar \
--logging.config=./logback.xml